package component:plugin;

use wasi:io/poll@0.2.2;

interface types {
  /// The Event type.
  record event {
    /// The variable name
    name: string,
    value: string
  }
}

interface host {
  use types.{event};
  use poll.{pollable};

  /// emit an event.
  emit: func(evt: event);

  /// get the unix timestamp
  now: func() -> s64;

  /// Sleep for a number of milliseconds.
  subscribe-duration: func(ms: u64) -> pollable;
}

interface run {

  /// loads just the XML like markdown
  load: func() -> string;

  /// the current date time
  datetime: func() -> string;

  /// Tick away with each second.
  ticker: func() -> bool;
}

/// An example world for the component to target.
world plugin-world {

  use types.{event};

  /// Import the poll interface.
  import poll;

  /// Import the event handler.
  import host;

  export run;
  
}
